config/routes.rb
Sprinker::Application.routes.draw do

  get "sprinkler/delete_all_rows"

  get "charts/moisture"

  get "charts/zone"

  get "charts/zones"

  get "charts/all"

  match '/sprinkler/start',    to: 'sprinkler#start'
  match '/sprinkler/stop',     to: 'sprinkler#stop'
  match '/sprinkler/moisture', to: 'sprinkler#moisture'

  get "sprinkler/deleteAllRows"

  resources :zone_entries

end

app/models/moisture.rb
# == Schema Information
#
# Table name: moistures
#
#  id         :integer          not null, primary key
#  value      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Moisture < ActiveRecord::Base
  attr_accessible :value, :moisture
  
end

app/models/zone_entry.rb
class ZoneEntry < ActiveRecord::Base
  attr_accessible :duration, :zone
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def moisture

    @title="Moisture voltage levels"

    @moistureValues = Array.new()
    Moisture.find_each do |x|
      a = Array.new()
      a.push(x[:created_at].to_time)
      a.push(x[:moisture].to_f)
      @moistureValues.push(a)
    end

  end

  def zone
  end

  def zones
  end

  def all
    @title="Sprinkler system"

    @moistureValues = Array.new()
    Moisture.find_each do |x|
      a = Array.new()
      a.push(x[:created_at].to_time)
      a.push(x[:moisture].to_f)
      @moistureValues.push(a)
    end

    @zoneArray = ZoneEntry.where(:zone => 1)

    i = 0
    @onValues = Array.new()
    ZoneEntry.find_each do |x|
      i = i + 1
      a = Array.new()
      a.push(x[:created_at].to_time)
      @onValues.push(a)
    end

    @zone1Values = Array.new()
    ZoneEntry.find_each do |x|
      a = Array.new()
      a.push(x[:created_at].to_time)
      a.push(x[:duration].to_f)
      @zone1Values.push(a)
    end
  end
end

app/controllers/sprinkler_controller.rb
# this is the one I want to start working with

class SprinklerController < ApplicationController

  def delete_all_rows
    #Moisture.delete_all
    #ZoneEntry.delete_all
    truncateOldRows()
    Moisture.delete_all(["value < ?", 1.0]) 
  end

  def truncateOldRows
    # Fetch your latest N records (to stay within 70% of 10k limit)
    days = 14;
    seconds = days * 24 * 60 * 60
    Moisture.delete_all(["created_at < ?", Time.now - seconds]) 
    ZoneEntry.delete_all(["created_at < ?", Time.now - seconds]) 
  end

  # called when the sprinkler zone is turned on
  def start
    # just logs the moisture value for now, 
    # time information is logged in stop
    truncateOldRows()
    if (params.has_key?(:moisture))  
      @moistureEntry = Moisture.new(:moisture => params[:moisture])
      @moistureEntry.save
    end
  end

  # /stop?zone=6&duration=123&moisture=1.23
  def stop
    truncateOldRows()
    if (params.has_key?(:moisture))  
      @moistureEntry = Moisture.new(:moisture => params[:moisture])
      @moistureEntry.save
    end
    if (params.has_key?(:zone) && params.has_key?(:duration))  
      @zoneEntry = ZoneEntry.new(:zone => params[:zone], :duration => params[:duration])
      @zoneEntry.save
    end
  end

  # for stand alone moisture data updates
  def moisture
    truncateOldRows()
    if (params.has_key?(:moisture))  
      @moistureEntry = Moisture.new(:moisture => params[:moisture])
      @moistureEntry.save
    end
  end

end

app/controllers/sprinkler_zones_controller.rb
class SprinklerZonesController < ApplicationController
  def log
  end
end

app/controllers/zone_entries_controller.rb
class ZoneEntriesController < ApplicationController
  # GET /zone_entries
  # GET /zone_entries.json
  def index
    @zone_entries = ZoneEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zone_entries }
    end
  end

  # GET /zone_entries/1
  # GET /zone_entries/1.json
  def show
    @zone_entry = ZoneEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zone_entry }
    end
  end

  # GET /zone_entries/new
  # GET /zone_entries/new.json
  def new
    @zone_entry = ZoneEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zone_entry }
    end
  end

  # GET /zone_entries/1/edit
  def edit
    @zone_entry = ZoneEntry.find(params[:id])
  end

  # POST /zone_entries
  # POST /zone_entries.json
  def create
    @zone_entry = ZoneEntry.new(params[:zone_entry])

    respond_to do |format|
      if @zone_entry.save
        format.html { redirect_to @zone_entry, notice: 'Zone entry was successfully created.' }
        format.json { render json: @zone_entry, status: :created, location: @zone_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @zone_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zone_entries/1
  # PUT /zone_entries/1.json
  def update
    @zone_entry = ZoneEntry.find(params[:id])

    respond_to do |format|
      if @zone_entry.update_attributes(params[:zone_entry])
        format.html { redirect_to @zone_entry, notice: 'Zone entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zone_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zone_entries/1
  # DELETE /zone_entries/1.json
  def destroy
    @zone_entry = ZoneEntry.find(params[:id])
    @zone_entry.destroy

    respond_to do |format|
      format.html { redirect_to zone_entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/sprinkler_helper.rb
module SprinklerHelper
end

app/helpers/sprinkler_zones_helper.rb
module SprinklerZonesHelper
end

app/helpers/zone_entries_helper.rb
module ZoneEntriesHelper
end

app/views/charts/all.html.erb
<!---
Setting the chart up in javascript because getting at the xAxis labels
for datetime is difficult in ruby
-->

<script type="text/javascript">
  (function() {
    var onload = window.onload;
    window.onload = function() {
      if (typeof onload == "function") onload();
      var options, chart;
      options = { "title": { "text": "<%= @title %>" },"legend": { "layout": "vertical","style": {  } },"xAxis": { "type": "datetime" },"yAxis": { "title": { "text": null },"labels": {  } },"tooltip": { "enabled": true },"credits": { "enabled": false },"plotOptions": { "areaspline": {  } },"chart": { "defaultSeriesType": "line","renderTo": "my_id" },"subtitle": {  },"series": [

        {"name":"voltage", "data":<%= @moistureValues.map{ |f| [(f[0].to_datetime.to_i + Time.zone_offset('CST')) * 1000, f[1] ] }.inspect %>},
        {"name":"zone1", "type":"scatter", "marker": {
                        "symbol": 'url(http://www.highcharts.com/demo/gfx/snow.png)'
                    },
        "data":<%= @onValues.map{ |f| [(f[0].to_datetime.to_i + Time.zone_offset('CST')) * 1000, 0.0 ] }.inspect %>}

        ]
      };
    chart = new Highcharts.Chart(options);
    };
  })()
</script>

<div id="my_id"></div>

app/views/charts/moisture.html.erb
<!---
Setting the chart up in javascript because getting at the xAxis labels
for datetime is difficult in ruby
-->

<script type="text/javascript">
  (function() {
    var onload = window.onload;
    window.onload = function(){
    if (typeof onload == "function") onload();
      var options, chart;
      options = { "title": { "text": "<%= @title %>" },"legend": { "layout": "vertical","style": {  } },"xAxis": { "type": "datetime" },"yAxis": { "title": { "text": null },"labels": {  } },"tooltip": { "enabled": true },"credits": { "enabled": false },"plotOptions": { "areaspline": {  } },"chart": { "defaultSeriesType": "line","renderTo": "my_id" },"subtitle": {  },"series": [{ "name": "voltage","data": 

      <%= @moistureValues.map{ |f| [(f[0].to_datetime.to_i + Time.zone_offset('CST')) * 1000, f[1] ] }.inspect %>
    }] };
    chart = new Highcharts.Chart(options);
    };
  })()
</script>

<div id="my_id"></div>

app/views/charts/zone.html.erb
<h1>Charts#zone</h1>
<p>Find me in app/views/charts/zone.html.erb</p>

app/views/charts/zones.html.erb
<h1>Charts#zones</h1>
<p>Find me in app/views/charts/zones.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sprinker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :highcharts %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sprinkler/delete_all_rows.html.erb
<h1>Sprinkler#delete_all_rows</h1>
<p>Find me in app/views/sprinkler/delete_all_rows.html.erb</p>

app/views/sprinkler/moisture.html.erb
<h1>Sprinkler#moisture</h1>
<p>value = <%= @moistureEntry.moisture %></p>

app/views/sprinkler/start.html.erb
<h1>Sprinkler#start</h1>
<p>Find me in app/views/sprinkler/start.html.erb</p>

app/views/sprinkler/stop.html.erb
<h1>Sprinkler#stop</h1>
<p>Find me in app/views/sprinkler/stop.html.erb</p>

app/views/sprinkler/zone_data.html.erb
<h1>Sprinkler#zone_data</h1>
<p>Find me in app/views/sprinkler/zone_data.html.erb</p>

app/views/sprinkler_zones/log.html.erb
<h1>SprinklerZones#log</h1>
<p>Find me in app/views/sprinkler_zones/log.html.erb</p>

app/views/zone_entries/_form.html.erb
<%= form_for(@zone_entry) do |f| %>
  <% if @zone_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone_entry.errors.count, "error") %> prohibited this zone_entry from being saved:</h2>

      <ul>
      <% @zone_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zone %><br />
    <%= f.number_field :zone %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zone_entries/edit.html.erb
<h1>Editing zone_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone_entry %> |
<%= link_to 'Back', zone_entries_path %>

app/views/zone_entries/index.html.erb
<h1>Listing zone_entries</h1>

<table>
  <tr>
    <th>Zone</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zone_entries.each do |zone_entry| %>
  <tr>
    <td><%= zone_entry.zone %></td>
    <td><%= zone_entry.duration %></td>
    <td><%= link_to 'Show', zone_entry %></td>
    <td><%= link_to 'Edit', edit_zone_entry_path(zone_entry) %></td>
    <td><%= link_to 'Destroy', zone_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zone entry', new_zone_entry_path %>

app/views/zone_entries/new.html.erb
<h1>New zone_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', zone_entries_path %>

app/views/zone_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Zone:</b>
  <%= @zone_entry.zone %>
</p>

<p>
  <b>Duration:</b>
  <%= @zone_entry.duration %>
</p>


<%= link_to 'Edit', edit_zone_entry_path(@zone_entry) %> |
<%= link_to 'Back', zone_entries_path %>